version: "3.9"
services:
  postgres:
    container_name: spring_postgres_biblioteca_jwt
    restart: on-failure
    image: postgres:12.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - TZ=America/Bogota
      - PGTZ=America/Bogota
    volumes:
      - ./db-data:/var/lib/postgresql/data